services:
  - type: web
    name: consulta-cep
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    region: oregon
    healthCheckPath: /
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m
